name: cv_project
channels:
  - defaults
dependencies:
  - numpy
  - scikit-image
  - scipy
  - matplotlib
  - python=3.9
  - jupyter
  - ipympl
  - pip
  - pip:
    - opencv-python
    - imutils
    - spectral
    - torch
    - torchvision